# Stage 1: Build
FROM maven:3.9.4-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests -DfinalName=app

# Stage 2: Production image
FROM openjdk:21-jdk-slim AS prod
WORKDIR /app

COPY --from=builder /app/target/app.jar app.jar

EXPOSE 8888

# set profile active
ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["java", "-jar", "app.jar"]
