
spring:
  application:
    name: cloud-config
  profiles:
    include: native,jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/dish_builder_db?options=-c%20TimeZone=Asia/Ho_Chi_Minh
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: config_schema
    locations: classpath:db/migration
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          order: 1
        jdbc:
          sql:
            SELECT key, value FROM config_schema.ws_properties prop WHERE (application=? OR application='all-services')  AND profile=? AND label=?
          order: 2
        default-profile: jdbc
      retry:
        max-attempts: 20
  jackson:
    time-zone: Asia/Ho_Chi_Minh
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.jdbc.core: DEBUG   # if using JDBC backend